<h2>TRANSFER LEARNING</h2>

In [1]:
import warnings
warnings.filterwarnings('ignore')

import keras
import pandas as pd
import numpy as np

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras.models import Sequential, Model, load_model
from keras.layers import Input, Dense

Using TensorFlow backend.


In [2]:
classifier = load_model('./models/classifier_model.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [55]:
df = pd.read_csv("./my_code/norm_dataset/r183c09s01_normalised.csv")

list_col1 = list(df.columns.values)
df.shape

(3758, 126)

In [4]:
#df2  = pd.read_csv("./final_data/r183c12s04_normalised.csv")
#list_col2 = list(df2.columns.values)

In [17]:
#drop timestamp col and divide df into anomaly df and no anomaly df
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]

In [18]:
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [19]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)

In [36]:
def assign_class(predicted_probabilities, threshold=0.5):
    classes = []
    for i in range(len(predicted_probabilities)):
        if(predicted_probabilities[i] >= threshold):
            classes.append(1)
        else:
            classes.append(0)
    return np.asarray(classes)

In [37]:
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [41]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))


Accuracy :9.333333333333334
f1Score: 0.17073170731707318


In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels_An, classes_An)

array([[ 0,  0],
       [68,  7]])

In [53]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))


Accuracy :96.44311702416508
f1Score: 0.9818935729094679


In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels_noAn, classes_NoAn)

array([[3552,  131],
       [   0,    0]])

In [46]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)

In [47]:
predict_prob = classifier.predict(df_total)

In [48]:
classes = assign_class(predict_prob)

In [52]:
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))


Accuracy :94.70463012240553
f1Score: 0.9546490770568218


In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3552,  131],
       [  68,    7]])