In [1]:
import warnings
warnings.filterwarnings('ignore')

import keras
import pandas as pd
import numpy as np

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras.models import Sequential, Model, load_model
from keras.layers import Input, Dense

Using TensorFlow backend.


In [2]:
classifier = load_model('./models/classifier_model.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


<h2> Node r183c09s03 </h2>

In [22]:
df = pd.read_csv("./my_code/norm_dataset/r183c09s03_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3758, 126)

In [5]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [6]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)

In [16]:
def assign_class(predicted_probabilities, threshold=0.5):
    classes = []
    for i in range(len(predicted_probabilities)):
        if(predicted_probabilities[i] >= threshold):
            classes.append(1)
        else:
            classes.append(0)
    return np.asarray(classes)

classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [17]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :0.0
f1Score: 0.0


In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels_An, classes_An)

array([[ 0,  0],
       [75,  0]])

In [19]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))


Accuracy :99.94569644311703
f1Score: 0.9997284084736556


In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels_noAn, classes_NoAn)

array([[3681,    2],
       [   0,    0]])

In [21]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))


Accuracy :97.95103778605642
f1Score: 0.9698982986047743


In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3681,    2],
       [  75,    0]])

<h2> Node r183c09s04 </h2>

In [25]:
df = pd.read_csv("./my_code/norm_dataset/r183c09s04_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3759, 126)

In [26]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [27]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)

In [28]:
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [29]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :9.333333333333334
f1Score: 0.17073170731707318


In [30]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.5928338762215
f1Score: 0.9979600163198695


In [31]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :97.79196594839053
f1Score: 0.9719662492404658


In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3669,   15],
       [  68,    7]])

<h2> Node r183c10s01 </h2>

In [36]:
df = pd.read_csv("./my_code/norm_dataset/r183c10s01_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3760, 126)

In [37]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [38]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [39]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :25.333333333333336
f1Score: 0.4042553191489362


In [40]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :62.469470827679785
f1Score: 0.7689994989143143


In [41]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :61.72872340425531
f1Score: 0.7471894901365168


In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[2302, 1383],
       [  56,   19]])

<h2> Node r183c10s02 </h2>


In [43]:
df = pd.read_csv("./my_code/norm_dataset/r183c10s02_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3756, 126)

In [44]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [45]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [46]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :34.66666666666667
f1Score: 0.5148514851485149


In [47]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.48383591415376
f1Score: 0.9974125017023016


In [48]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :98.18956336528221
f1Score: 0.9796693256158113


In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3662,   19],
       [  49,   26]])

<h2> Node r183c10s03 </h2>

In [50]:
df = pd.read_csv("./my_code/norm_dataset/r183c10s03_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3758, 126)

In [51]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [52]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [53]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :0.0
f1Score: 0.0


In [54]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.89139288623404
f1Score: 0.9994566693833198


In [55]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :97.89781798829165
f1Score: 0.9696320119695526


In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3679,    4],
       [  75,    0]])

<h2> r183c11s01 </h2> 

In [58]:
df = pd.read_csv("./my_code/norm_dataset/r183c11s01_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3151, 126)

In [59]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [60]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [61]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :0.0
f1Score: 0.0


In [62]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.9675535366645
f1Score: 0.9998377413597274


In [63]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :97.7784830212631
f1Score: 0.9671158044657666


In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3081,    1],
       [  69,    0]])

<h2>r183c11s02</h2>

In [66]:
df = pd.read_csv("./my_code/norm_dataset/r183c11s02_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3679, 126)

In [67]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [68]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [69]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :0.0
f1Score: 0.0


In [70]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.94459833795014
f1Score: 0.999722914934885


In [71]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :98.07012775210654
f1Score: 0.9716842628931099


In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3608,    2],
       [  69,    0]])

<h2>r183c11s03</h2>

In [74]:
df = pd.read_csv("./my_code/norm_dataset/r183c11s03_normalised.csv")
list_col1 = list(df.columns.values)
df.shape

(3678, 126)

In [75]:
df = df.drop("timestamp",axis=1)
df_noAn = df[df.label==0]
df_An = df[df.label==1]
labels_noAn = df_noAn["label"]
labels_An = df_An["label"]
#Drop label col for prediction
df_noAn = df_noAn.drop("label",axis=1)
df_An = df_An.drop("label",axis=1)

In [76]:
predict_prob_noAn = classifier.predict(df_noAn)
predict_prob_An = classifier.predict(df_An)
classes_An = assign_class(predict_prob_An)
classes_NoAn = assign_class(predict_prob_noAn)

In [77]:
#metrics for df anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_An,classes_An)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_An,classes_An)))

Accuracy :1.4492753623188406
f1Score: 0.02857142857142857


In [78]:
#metrics for df no anomaly
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels_noAn,classes_NoAn)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels_noAn,classes_NoAn,average='weighted')))

Accuracy :99.94458298697701
f1Score: 0.9997228381374723


In [79]:
#metrics for total dataset
labels = df["label"]
df_total = df.drop("label",axis=1)
predict_prob = classifier.predict(df_total)
classes = assign_class(predict_prob)
from sklearn.metrics import accuracy_score
print("Accuracy :"+str(accuracy_score(labels,classes)*100))
from sklearn.metrics import f1_score
print("f1Score: "+str(f1_score(labels,classes,average='weighted')))

Accuracy :98.09679173463839
f1Score: 0.9723311038906551


In [80]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels, classes)

array([[3607,    2],
       [  68,    1]])